using UnityEngine;

/// <summary>
/// Class <c>BuildingData</c> is a scriptable object containing the different information defining a building behaviours.
/// </summary>
[CreateAssetMenu(fileName = "Data", menuName = "ScriptableObjects/BuildingData", order = 3)]
public class BuildingData : ScriptableObject
{
    /// <summary>
    /// Instance variable <c>id</c> represents the identifier value of the building.
    /// </summary>
    public int id = -1;
    
    /// <summary>
    /// Instance variable <c>icon</c> is a Unity <c>Sprite</c> component representing the UI icon of the building.
    /// </summary>
    [Header("Building display")]
    public Sprite icon;
    
    /// <summary>
    /// Instance variable <c>buildingPreview</c> is a Unity <c>GameObject</c> object representing the model preview of the building.
    /// </summary>
    public GameObject buildingPreview;

    /// <summary>
    /// Instance variable <c>price</c> represents the price value of the building.
    /// </summary>
    [Header("Main building data")]
    public int price = 100;
    
    /// <summary>
    /// Instance variable <c>maxHealth</c> represents the maximum quantity of health own by the unit instance.
    /// </summary>
    public int maxHealth = 100;
    
    /// <summary>
    /// Enum variable <c>BuildingType</c> representing the different building type available in the game.
    /// </summary>
    public enum BuildingType
    {
        ResourceGenerator,
        UnitSpawner
    }

    /// <summary>
    /// Instance variable of the <c>BuildingType</c> enumeration, <c>buildingType</c> represents the type of the building.
    /// </summary>
    [Header("Specific building data")]
    public BuildingType buildingType;

    /// <summary>
    /// Instance variable <c>unitPrefab</c> is a Unity <c>GameObject</c> component representing the unit prefabricated object to be instantiated by the unit spawner.
    /// </summary>
    public Unit unitPrefab;
    
    /// <summary>
    /// Instance variable <c>maxUnitQueue</c> represents the maximum size value of unit to be stored in the unit spawner queue.
    /// </summary>
    public int maxUnitQueue = 5;

    /// <summary>
    /// Instance variable <c>spawnMoveRange</c> represents the range value of unit movements around the spawn point of the unit spawner.
    /// </summary>
    public float spawnMoveRange = 7.0f;
    
    /// <summary>
    /// Instance variable <c>unitSpawnDuration</c> represents the duration value of unit to spawn on unit spawner.
    /// </summary>
    public float unitSpawnDuration = 5.0f;
    
    /// <summary>
    /// Instance variable <c>resourcesPerInterval</c> represents the resources quantity value generated by the building at each interval.
    /// </summary>
    public int resourcesPerInterval = 10;

    /// <summary>
    /// Instance variable <c>interval</c> represents the interval time value between two resources generation.
    /// </summary>
    public float interval = 2f;
}
